stages:
  - update_headers

update_headers:
  stage: update_headers
  image: ubuntu:latest
  before_script:
    - apt-get update && apt-get install -y git
    - git config --global user.name "gitlab-ci"
    - git config --global user.email "gitlab-ci@gitlab.com"
  script:
    - for file in $(git ls-files '*.sql'); do
        if grep -q "\$LastChangedRevision:" "$file"; then
          VERSION=$(grep "\$LastChangedRevision:" "$file" | awk '{print $3}')
          NEW_VERSION=$((VERSION + 1))
          HEADER: |
  ------------------------
  -- Version
  --     $LastChangedRevision: 4 $;
  --
  -- Date
  --     $LastChangedDate: $(date +"%Y-%m-%d %H:%M:%S %z (%a, %d %b %Y)") $;
  --
  -- Author
  --     $LastChangedBy: 777 $;
  ------------------------
          sed -i '1,/^--$/d' "$file"  # Remove existing headers
          echo -e "$HEADER\n$(cat "$file")" > "$file"
        fi
      done
    - git add .
    - git diff --staged --quiet || git commit -m "Updated SQL file headers with version increment"
    - git push
